### ISSUE TITLE
Service does not work anymore: "Wrong number of args (0) passed to: rss/enclosure"

### ISSUE THREAD

**Issue by stoerr** [djui/qcast#51]
Hi!

Thank you for this very helpful service!
Unfortunately, http://infoqcast.herokuapp.com/ seems not to work anymore: calling
https://infoqcast.herokuapp.com/feed/audio
or
https://infoqcast.herokuapp.com/feed/video
yields a HTTP 500 with the error message
"Wrong number of args (0) passed to: rss/enclosure"
Could you perhaps fix this?

Thank you so much!

**Comment by djui** [comment]
Will have a look in a bit.

**Comment by JKesMc9tqIQe9M** [comment]
I think we'd just need to add the missing 'http:' to protocol-less URLs. @djui are you already taking a look at the fix or should I give it a shot? Thanks!

**Comment by JKesMc9tqIQe9M** [comment]
Submitted bug fix here: #52

**Comment by JKesMc9tqIQe9M** [comment]
@djui any chance you can take a quick look at the PR I made to fix this? Thanks!

**Comment by djui** [comment]
@stoerr I merged @JKesMc9tqIQe9M fix; his hypothesis was correct.

@JKesMc9tqIQe9M I'm sorry for all the late merged. I have little time for this project; I wish I could give it a little more love.

**Comment by djui** [comment]
Closed by https://github.com/djui/qcast/pull/52
