### ISSUE TITLE
Publish new presentation updates via Hooks new developer API

### ISSUE THREAD

**Issue by djui** [djui/qcast#55]
[Hooks](http://www.gethooksapp.com) app started to open their [developer API](https://hooksapi.readme.io). An integration would be nice, so people not using a podcast client to get updates can get notified when new presentations are available.

**Comment by djui** [comment]
Closed by 169d7ab5dda00b85e6d317e2f56faa29c47eba40 @i-s-o-g-r-a-m Could you have an eye on your feed if everything is still working alright? Thanks.

**Comment by witte-de-with** [comment]
@djui Looking good so far! Thanks!!
